[project]
name = "dl-bio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bioservices>=1.12.1",
    "dlfb",
    "goatools>=1.5.2",
    "graphviz>=0.21",
    "ipykernel>=7.1.0",
    "jax[cuda12]>=0.8.2",
    "matplotlib>=3.10.8",
    "networkx>=3.6.1",
    "numpy>=2.4.1",
    "obonet>=1.1.1",
    "transformers>=4.57.6",
    "datasets>=3.0",
    "accelerate>=1.0",
    "seaborn>=0.13.2",
    "biopython>=1.86",
    "scikit-learn>=1.8.0",
    "umap-learn>=0.5.11",
    "pandas>=2.3.3",
    "pyarrow>=22.0.0",
    "flax>=0.12.5",
    "optax>=0.2.6",
    "plotly>=6.6.0",
    "cellxgene-census>=1.17.0",
    "scanpy>=1.11.5",
    "tiledb>=0.36.1",
    "rdkit>=2026.3.3",
]

[tool.uv.workspace]
members = [
    "dlfb",
]

[tool.uv.sources]
dlfb = { workspace = true }
